title: genesthai 
email: brendan.lane27@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  *nix, AWS, Elastic, Ansible, coding, Minecraft and other nerd ramblings.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://genestha.io" # the base hostname & protocol for your site, e.g. http://example.com
social:
  type: Person
  name: "Brendan Lane"
  links:
    - "https://twitter.com/brelane27"
    - "https://github.com/brelane33" 

author:
  name: "Brendan"
  bio: "Infrastructure Engineer"
  location: "Texas"
  links:
    - label: "Twitter" 
      url: "https://twitter.com/brelane27"
    - label: "GitHub"
      url: "https://github.com/brelane33" 

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

minimal_mistakes_skin: "dirt"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false 
      share: true
      related: true


# Analytics
google_analytics: UA-170314260-1
google_site_verification: google-site-verification=niAQfEwPBIw30_iFZfe090pj2POInra4-DZogwIQIwY
